// Generated by ReScript, PLEASE EDIT WITH CARE


function radiusToUnits(radius) {
  if (radius <= 0) {
    return 0;
  } else {
    return Math.pow(radius, 2) / 50;
  }
}

function unitsToRadius(units) {
  if (units <= 0) {
    return 0;
  } else {
    return Math.sqrt(units * 50);
  }
}

function radiusToGrowthPerSecond(radius) {
  return radius / 50;
}

function grow(cell, timeInMs) {
  var unitInc = cell.radius / 50 * 1000 / timeInMs;
  var newUnits = cell.units + unitInc;
  return {
          id: cell.id,
          ownerId: cell.ownerId,
          units: newUnits,
          radius: cell.radius,
          position: cell.position
        };
}

function move(bubble) {
  return bubble;
}

var radiusToUnitsFixPoint = 50;

var unitGrowthRadius = 50;

var defaultBubbleSpeedInPixelPerSecond = 90;

export {
  radiusToUnitsFixPoint ,
  radiusToUnits ,
  unitsToRadius ,
  unitGrowthRadius ,
  radiusToGrowthPerSecond ,
  grow ,
  move ,
  defaultBubbleSpeedInPixelPerSecond ,
  
}
/* No side effect */
