// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as SpreadGameCollisions from "./SpreadGameCollisions.bs.js";

function SpreadGame(funarg) {
  var include = SpreadGameCollisions.SpreadGameCollisions(funarg);
  var collideBubbles = include.collideBubbles;
  var collideCells = include.collideCells;
  var step = function (state, timeInMs) {
    var newCells = state.cells.map(function (cell) {
          return Curry._2(funarg.grow, cell, timeInMs);
        });
    var newBubbles = state.bubbles.map(function (bubble) {
          return Curry._2(funarg.move, bubble, timeInMs);
        });
    var match = Curry._1(collideBubbles, newBubbles);
    var match$1 = Curry._2(collideCells, match[0], newCells);
    return [
            {
              cells: match$1[1],
              bubbles: match$1[0]
            },
            match$1[2].concat(match[1])
          ];
  };
  return {
          step: step
        };
}

export {
  SpreadGame ,
  
}
/* No side effect */
