// Generated by ReScript, PLEASE EDIT WITH CARE


function $$new(x, y) {
  return [
          x,
          y
        ];
}

function add(v1, v2) {
  return [
          v1[0] + v2[0] | 0,
          v1[1] + v2[1] | 0
        ];
}

export {
  $$new ,
  add ,
  
}
/* No side effect */
