// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Vector2D from "./Vector2D.bs.js";

function eucl(direction) {
  return [
          Math.cos(direction.angle),
          Math.sin(direction.angle)
        ];
}

function toVector(direction) {
  var match = eucl(direction);
  return Vector2D.$$new(match[0], match[1]);
}

export {
  eucl ,
  toVector ,
  
}
/* No side effect */
