// Generated by ReScript, PLEASE EDIT WITH CARE


function $$new(x, y) {
  return [
          x,
          y
        ];
}

function eucl(v) {
  return [
          v[0],
          v[1]
        ];
}

function add(v1, v2) {
  var match = eucl(v1);
  var match$1 = eucl(v2);
  return [
          match[0] + match$1[0],
          match[1] + match$1[1]
        ];
}

function sub(v1, v2) {
  var match = eucl(v1);
  var match$1 = eucl(v2);
  return [
          match[0] - match$1[0],
          match[1] - match$1[1]
        ];
}

function mul(v1, v2) {
  var match = eucl(v1);
  var match$1 = eucl(v2);
  return match[0] * match$1[0] + match[1] * match$1[1];
}

function scalarMul(v1, a) {
  var match = eucl(v1);
  return [
          match[0] * a,
          match[1] * a
        ];
}

function distance(v1, v2) {
  var v = sub(v1, v2);
  return Math.sqrt(mul(v, v));
}

var zero = [
  0,
  0
];

export {
  $$new ,
  eucl ,
  add ,
  mul ,
  scalarMul ,
  distance ,
  zero ,
  
}
/* No side effect */
